server:
    port: 8082
spring.redis:
    host: localhost
    port: 6379
throttle:
    period: ${PERIOD} # in ms
    default_rate_value: ${DEFAULT_RATE} # n of calls
    service: ${SERVICE_NAME}
    bucket_renovation_period: ${BUCKET_RENOVATION_PERIOD}
    bucket_id: ${BUCKET_ID}
